/**
 * Web article parser using Mozilla's Readability.js.
 *
 * The bundled source (generated by scripts/bundle-readability.js)
 * is injected into a WebView that loads the target URL.
 * Readability parses the live DOM and returns clean article HTML.
 */

import { READABILITY_JS } from './readabilityBundle';

export interface ParsedArticle {
  title: string;
  author: string | null;
  content: string; // cleaned HTML
  textContent: string; // plain text
  excerpt: string | null;
  siteName: string | null;
  length: number; // character count
}

/**
 * JavaScript to inject into a WebView *after* the page loads.
 * 1. Loads Readability into the global scope
 * 2. Runs it against the current DOM
 * 3. Posts the result back to React Native via postMessage
 */
export const READABILITY_EXTRACTION_JS = `
${READABILITY_JS}
(function() {
  try {
    var documentClone = document.cloneNode(true);
    var article = new window.Readability(documentClone).parse();
    if (!article) {
      window.ReactNativeWebView.postMessage(JSON.stringify({
        type: 'readability_error',
        error: 'Readability could not parse this page',
      }));
      return;
    }

    var metaSiteName = document.querySelector('meta[property="og:site_name"]');

    window.ReactNativeWebView.postMessage(JSON.stringify({
      type: 'readability_result',
      title: article.title || document.title,
      author: article.byline || null,
      content: article.content,
      textContent: article.textContent,
      excerpt: article.excerpt || null,
      siteName: metaSiteName ? metaSiteName.content : window.location.hostname,
      length: (article.textContent || '').length,
      url: window.location.href,
    }));
  } catch(e) {
    window.ReactNativeWebView.postMessage(JSON.stringify({
      type: 'readability_error',
      error: e.message,
    }));
  }
})();
true;
`;

/**
 * Estimate reading time in minutes based on word count.
 * Average reading speed: ~250 words per minute.
 */
export function estimateReadingTime(text: string): number {
  const wordCount = text.split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(wordCount / 250));
}
